### ISSUE TITLE
Cache ADS Mode Snapshot Consistency Question

### ISSUE THREAD

**Issue by dfjones** [envoyproxy/go-control-plane#119]
We've run into an issue when using Envoy with a Snapshot Cache configured for ADS mode and statically defined clusters that are discovered through EDS.

This comes from trying to use EDS to discover the endpoints for the tracing service, for instance, in our Envoy config we have:
```
tracing:
  http:
    name: envoy.zipkin
    config:
      collector_cluster: trace-collector
      collector_endpoint: /api/v1/spans
```
And then a static cluster configured for EDS:

```
static_resources:
  clusters:
  - name: trace-collector
    connect_timeout: 0.25s
    lb_policy: ROUND_ROBIN
    type: EDS
    eds_cluster_config:
      eds_config:
        api_config_source:
          api_type: GRPC
          grpc_services:
            - envoy_grpc:
                cluster_name: xds_cluster
```

We've noticed that if we configure the rest of Envoy's CDS and EDS to use the ADS stream, we run into a deadlock on initial Envoy boot.

I've traced the request flow and it goes like this:
* Envoy looks up static `trace-collector` endpoints through EDS. 
* Cache responds normally, Envoy moves on to dynamic CDS over ADS.
*CDS over ADS response is served from go-control-plane cache with a list of clusters including the `trace-collector`. 
* Envoy performs EDS over ADS but does not request the `trace-collector` resource, since this was already discovered separately.
* go-control-plane cache does not respond to the EDS over ADS because the requested resource names are not a superset of the snapshot's resources, the logic found here: https://github.com/envoyproxy/go-control-plane/blob/master/pkg/cache/simple.go#L220

To work around this issue, we have to exclude `trace-collector` from the snapshot used for ADS.

My question is, what is the motivation behind ensuring the requested resources are a superset of the cached snapshot resources? My gut feeling is that the other way around makes more sense: the cached snapshot is a superset of the requested resources.
