### ISSUE TITLE
Consistency check fails for an envoy which has only RDS and CDS

### ISSUE THREAD

**Issue by budanm** [envoyproxy/go-control-plane#257]
Hi

I have an envoy proxy (ADS) which is having a static listener and it is using Route Discovery Service to discover routes and Cluster Discovery Service for discovering clusters that are referred to by the routes. 

However, prior to setting a snapshot for the node, I want to do a consistency check snapshot.Consistent(). But the consistency check fails continuously.

The reason I figured out is when I do a snapshot.GetSnapshot(nodeId), it gives the listeners slice as empty. The snapshot for that node is not containing any information about the components which are static. The check is failing [here](https://github.com/envoyproxy/go-control-plane/blob/338b635362ad7330aa72ae8b3d648d145a82b584/pkg/cache/snapshot.go#L91).

How do we resolve this ?

**Comment by alecholmez** [comment]
I think that is intentional, static resources don't make it back into the management server (your snapshot cache). So to fix this you will need to dynamically define those listeners. If you're using ADS I don't think you can utilize individual discovery mechanisms it's either all or none. What I would recommend you do is dump ADS, which is only needed for resource multiplexing or synchronization, and only use CDS and RDS. Which can be defined in an Envoy config like such:

```yaml
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 127.0.0.1, port_value: 9901 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 127.0.0.1, port_value: 10000 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: { cluster: some_service }
          http_filters:
          - name: envoy.router
  clusters:
  - name: some_service
    connect_timeout: 0.25s
    lb_policy: ROUND_ROBIN
    type: EDS
    eds_cluster_config:
      eds_config:
        api_config_source:
          api_type: GRPC
          grpc_services:
            envoy_grpc:
              cluster_name: xds_cluster
  - name: xds_cluster
    connect_timeout: 0.25s
    type: STATIC
    lb_policy: ROUND_ROBIN
    http2_protocol_options: {}
    upstream_connection_options:
      # configure a TCP keep-alive to detect and reconnect to the admin
      # server in the event of a TCP socket half open connection
      tcp_keepalive: {}
    load_assignment:
      cluster_name: xds_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 5678
```
And to use RDS you'd do something like:
```yaml
version_info: "0"
resources:
- "@type": type.googleapis.com/envoy.api.v2.RouteConfiguration
  name: local_route
  virtual_hosts:
  - name: local_service
    domains: ["*"]
    routes:
    - match: { prefix: "/" }
      route: { cluster: some_service }
```
