### ISSUE TITLE
Can't use header_to_metadata extension in envoy 

### ISSUE THREAD

**Issue by maksim-paskal** [envoyproxy/go-control-plane#351]
I was trying Unmarshal envoy config 

```
- name: envoy.filters.http.header_to_metadata
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.filters.http.header_to_metadata.v3.Config
    request_rules:
    - cookie: cookie
      on_header_present:
        metadata_namespace: envoy.lb
        key: version
        type: STRING
      on_header_missing:
        metadata_namespace: envoy.lb
        key: default
        value: 'true'
        type: STRING
      remove: false
```

with latest tag v0.9.6 using imported
```
github.com/envoyproxy/go-control-plane/envoy/extensions/filters/http/header_to_metadata/v3
```

and got error
```
unknown field "cookie"
```

master branch has valid proto file - problem in latest tag
