### ISSUE TITLE
Cannot get v3 to work for access logs or metrics

### ISSUE THREAD

**Issue by cgkades** [envoyproxy/go-control-plane#385]
I cannot get the v3 to work, but if I change it to v2 it does. Everything compiles Can you guys please tell me what I'm doing wrong? 

I even tried https://github.com/envoyproxy/go-control-plane/blob/master/pkg/test/v3/accesslog.go instead of my own code, and it doesn't work either. I added a New() function to it so I could call it easier from my main.go, and added a simple `log.Println("got a log")` statement inside of the `StreamAccessLogs` function so i could see that it's entering it:

```
func New() accessloggrpc.AccessLogServiceServer {
	return &AccessLogService{}
}
```

```
func (svc *AccessLogService) StreamAccessLogs(stream accessloggrpc.AccessLogService_StreamAccessLogsServer) error {
	var logName string
	log.Println("got a log")
<---SNIP--->
```

Here is the relevant part of my main()
```
        grpcServer := grpc.NewServer()

	v3.RegisterAccessLogServiceServer(grpcServer, New())
	
	listener, err := net.Listen("tcp", ":9191")
	if err != nil {
		log.Fatal().Msg(err.Error())
	}
	infoLogger.Msg("Starting Grpc Server")

	err = grpcServer.Serve(listener)
	if err != nil {
		fmt.Println(err)
	}

``` 
envoy.yaml
```
node:
  id: test-id
  cluster: test

admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  clusters:
    # the control plane (aggregated discovery service) cluster
    - name: xds_cluster
      type: STATIC
      http2_protocol_options:
        # disable header compression
        hpack_table_size: 0
      connect_timeout: 0.25s
      load_assignment:
        cluster_name: xds_cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    pipe:
                      path: /tmp/xds.sock

    # the access log service cluster
    - name: als_cluster
      type: STATIC
      http2_protocol_options:
        # disable header compression
        hpack_table_size: 0
      connect_timeout: 0.25s
      load_assignment:
        cluster_name: als_cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 9191

    # test cluster (httpbin)
    - name: httpbin
      connect_timeout: 1s
      type: LOGICAL_DNS
      dns_lookup_family: V4_ONLY
      lb_policy: LEAST_REQUEST
      load_assignment:
        cluster_name: httpbin
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: httpbin.org
                      port_value: 80
      max_requests_per_connection: 10000
      common_http_protocol_options:
        idle_timeout: 120s
      upstream_connection_options:
        tcp_keepalive:
          keepalive_time: 30
          keepalive_interval: 30

  # test listener
  listeners:
    - name: listener_test
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 9999
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                use_remote_address: true
                access_log:
                  - name: envoy.access_loggers.file
                    typed_config:
                      '@type': type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                      path: /dev/stdout
                  - name: envoy.access_loggers.http_grpc
                    typed_config:
                      '@type': type.googleapis.com/envoy.extensions.access_loggers.grpc.v3.HttpGrpcAccessLogConfig
                      common_config:
                        log_name: jag-access-log
                        grpc_service:
                          envoy_grpc:
                            cluster_name: als_cluster
                route_config:
                  name: default
                  response_headers_to_add:
                    - append: false
                      header:
                        key: x-envoy-downstream-remote-ip
                        value: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
                  virtual_hosts:
                    - name: default
                      domains: [ "*" ]
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: httpbin
                            retry_policy:
                              retry_on: gateway-error,reset,connect-failure,refused-stream
                              num_retries: 3
                              retry_host_predicate:
                                name: envoy.retry_host_predicates.previous_hosts
                              host_selection_retry_max_attempts: 3
                http_filters:
                  - name: envoy.filters.http.router
```

**Comment by EItanya** [comment]
Hello, you need to set the `TransportApiVersion`  in the grpc als config
```
                  - name: envoy.access_loggers.http_grpc
                    typed_config:
                      '@type': type.googleapis.com/envoy.extensions.access_loggers.grpc.v3.HttpGrpcAccessLogConfig
                      common_config:
                        log_name: jag-access-log
                        transport_api_version: V3
                        grpc_service:
                          envoy_grpc:
                            cluster_name: als_cluster
```
