### ISSUE TITLE
Create "all" package that imports all other packages to help dynamic proto resolution

### ISSUE THREAD

**Issue by cretz** [envoyproxy/go-control-plane#390]
When unmarshaling a yaml like:

```yaml
typed_config:
  "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
  path: my-access-log
```

or any other WKT "any" proto type, it uses a global registration system that is set on package init. So if you haven't imported https://godoc.org/github.com/envoyproxy/go-control-plane/envoy/extensions/access_loggers/file/v3, this will fail with something like:

    unable to resolve "type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog": "not found"

Of course a `import _ "github.com/envoyproxy/go-control-plane/envoy/extensions/access_loggers/file/v3"` solves just this use, but it doesn't help with general purpose "any" resolution or other dynamic type resolution. Many other libs have an "all" package that imports everything else.

I am doing a codegen internally to build this, but thought I'd toss the issue out here to see if y'all want to include it in this repo that is built as part of the envoy project's proto gen (can open on that repo if desired).
