### ISSUE TITLE
UpstreamTlsContext does not implement isTransportSocket_ConfigType

### ISSUE THREAD

**Issue by mooction** [envoyproxy/go-control-plane#405]
Hi everyone, I'm new to envoy & go-contorl-plane. I followed tutorials and I want to implement [this](https://github.com/envoyproxy/envoy/blob/main/examples/tls/envoy-http-https.yaml) YAML config:

```yaml
  clusters:
  - name: service-https
    connect_timeout: 0.25s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service-https
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: service-https
                port_value: 443
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
```

Then I used codes in [example/resource.go](https://github.com/envoyproxy/go-control-plane/blob/main/internal/example/resource.go), here is my code snippet:

```go
import (
    "time"

    "github.com/golang/protobuf/ptypes"

    cluster "github.com/envoyproxy/go-control-plane/envoy/config/cluster/v3"
    core "github.com/envoyproxy/go-control-plane/envoy/config/core/v3"
    endpoint "github.com/envoyproxy/go-control-plane/envoy/config/endpoint/v3"
    listener "github.com/envoyproxy/go-control-plane/envoy/config/listener/v3"
    route "github.com/envoyproxy/go-control-plane/envoy/config/route/v3"
    hcm "github.com/envoyproxy/go-control-plane/envoy/extensions/filters/network/http_connection_manager/v3"
    tls "github.com/envoyproxy/go-control-plane/envoy/extensions/transport_sockets/tls/v3"
    "github.com/envoyproxy/go-control-plane/pkg/cache/types"
    "github.com/envoyproxy/go-control-plane/pkg/cache/v3"
    "github.com/envoyproxy/go-control-plane/pkg/resource/v3"
    "github.com/envoyproxy/go-control-plane/pkg/wellknown"
)

func makeCluster() []types.Resource {
    return []types.Resource{
        &cluster.Cluster{
            Name:                 "cluster_google",
            ConnectTimeout:       ptypes.DurationProto(5 * time.Second),
            ClusterDiscoveryType: &cluster.Cluster_Type{
                Type: cluster.Cluster_LOGICAL_DNS,
            },
            LbPolicy:             cluster.Cluster_ROUND_ROBIN,
            LoadAssignment:       makeEndpoint(),
            DnsLookupFamily:      cluster.Cluster_V4_ONLY,
            TransportSocket:      &core.TransportSocket{
                Name:             wellknown.TransportSocketTls,
                ConfigType:       &tls.UpstreamTlsContext{
                    Sni:          "www.google.com",
                },
            },
        },
    }
}

func makeEndpoint() *endpoint.ClusterLoadAssignment {
    return &endpoint.ClusterLoadAssignment{
        ClusterName: "cluster_google",
        Endpoints: []*endpoint.LocalityLbEndpoints{{
            LbEndpoints: []*endpoint.LbEndpoint{{
                HostIdentifier: &endpoint.LbEndpoint_Endpoint{
                    Endpoint: &endpoint.Endpoint{
                        Address: &core.Address{
                            Address: &core.Address_SocketAddress{
                                SocketAddress: &core.SocketAddress{
                                    Protocol: core.SocketAddress_TCP,
                                    Address:  "www.google.com",
                                    PortSpecifier: &core.SocketAddress_PortValue{
                                        PortValue: 443,
                                    },
                                },
                            },
                        },
                    },
                },
            }},
        }},
    }
}
```

But it turns out an error:

```text
$ go run .
# main
./resource.go:58:17: cannot use envoy_extensions_transport_sockets_tls_v3.UpstreamTlsContext literal (type *envoy_extensions_transport_sockets_tls_v3.UpstreamTlsContext) as type envoy_config_core_v3.isTransportSocket_ConfigType in field value:
        *envoy_extensions_transport_sockets_tls_v3.UpstreamTlsContext does not implement envoy_config_core_v3.isTransportSocket_ConfigType (missing envoy_config_core_v3.isTransportSocket_ConfigType method)
```

Maybe I missed something, can you tell me how to fix it? Thank you.
