### ISSUE TITLE
xds server works with mostly static + dynamic RDS

### ISSUE THREAD

**Issue by hochuenw-dd** [envoyproxy/go-control-plane#444]
Hi, 
I have a static listener + dynamic route configuration which is similar to this one https://www.envoyproxy.io/docs/envoy/latest/configuration/overview/examples#mostly-static-with-dynamic-eds, the difference is mine is dynamic rds instead of dynamic eds

```
  - name: outbound_listener
    address:
      socket_address: { address: 0.0.0.0, port_value: 16000 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: egress_http
          codec_type: AUTO
          rds:
            route_config_name: outbound_route
            config_source:
              resource_api_version: V3
              api_config_source:
                api_type: GRPC
                transport_api_version: V3
                grpc_services:
                - envoy_grpc:
                    cluster_name: xds_cluster
          http_filters:
          - name: envoy.filters.http.router
```

Since I don't have any dynamic listeners, and I just have a dynamic route configuration, in my xDS server, I don't return any listener, and just return the route configuration which reference to `outbound_route`.

When I call cache.Consistent(), it complains with `"mismatched route reference and resource lengths: map[] != 1"` https://github.com/envoyproxy/go-control-plane/blob/main/pkg/cache/v3/snapshot.go#L184. My understanding is that I return one route config back, but it can not find any listener that references to the route since the xds server doesn't have any listener in the response. 

Is this expected? I feel like this is one use case that cache.consistent() method shouldn't complain here https://github.com/envoyproxy/go-control-plane/blob/main/pkg/cache/v3/snapshot.go#L182

Thanks for the support!!
