### ISSUE TITLE
idle grpc streams are closed when http2 connection keepalives are enabled

### ISSUE THREAD

**Issue by databus23** [envoyproxy/go-control-plane#449]
I noticed then when using go-control-plane and the cache is updated infrequently the grpc stream gets disconnected after about 2 minutes of idle time. When I update the cache with higher frequency this does not happen.
This looks to me like some sort of timeout in the grpc server but I can't figure out why this happens.
Is there a way to prevent this? I would like to avoid envoy to keep logging errors on a constant basis.

### Steps to reproduce the issue 

* envoy 1.18.3
* go-control-plane 0.9.9

#### Run envoy:
```
docker run --rm -p 9901:9901 -p 10000:10000 -v $PWD/config/envoy-minimal.yaml:/etc/envoy/envoy.yaml:ro  envoyproxy/envoy-alpine:v1.18.3
```
#### Run controlplane:
```
go run main.go
```

Leave it running for a few minutes to observe these logs:

```
# envoy:
[2021-06-15 11:17:16.784][1][info][main] [source/server/server.cc:745] all clusters initialized. initializing init manager
[2021-06-15 11:17:16.785][1][warning][main] [source/server/server.cc:642] there is no configured limit to the number of allowed active connections. Set a limit via the runtime key overload.global_downstream_max_connections
[2021-06-15 11:17:16.791][1][info][config] [source/server/listener_manager_impl.cc:888] all dependencies initialized. starting workers
[2021-06-15 11:19:21.954][1][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:101] StreamRoutes gRPC config stream closed: 13,
[2021-06-15 11:21:30.721][1][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:101] StreamRoutes gRPC config stream closed: 14, upstream connect error or disconnect/reset before headers. reset reason: connection termination
[2021-06-15 11:23:42.811][1][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:101] StreamRoutes gRPC config stream closed: 14, upstream connect error or disconnect/reset before headers. reset reason: connection termination
[2021-06-15 11:25:57.970][1][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:101] StreamRoutes gRPC config stream closed: 14, upstream connect error or disconnect/reset before headers. reset reason: connection termination
...

# grpc server:
2021/06/15 13:17:16 stream 1 open for type.googleapis.com/envoy.config.route.v3.RouteConfiguration
2021/06/15 13:19:21 stream 1 closed
2021/06/15 13:19:22 stream 2 open for type.googleapis.com/envoy.config.route.v3.RouteConfiguration
2021/06/15 13:21:30 stream 2 closed
2021/06/15 13:21:30 stream 3 open for type.googleapis.com/envoy.config.route.v3.RouteConfiguration
2021/06/15 13:23:42 stream 3 closed
2021/06/15 13:23:43 stream 4 open for type.googleapis.com/envoy.config.route.v3.RouteConfiguration
2021/06/15 13:25:57 stream 4 closed
...

```

envoy bootstrap config:
```
node:
  id: test-id
  cluster: test
admin:
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 9901
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          rds:
            route_config_name: "test-route"
            config_source:
              resource_api_version: V3
              api_config_source:
                api_type: GRPC
                transport_api_version: V3
                grpc_services:
                  envoy_grpc:
                    cluster_name: xds_cluster
          http_filters:
          - name: envoy.filters.http.router
  clusters:
  - name: xds_cluster
    connect_timeout: 2s
    type: LOGICAL_DNS
    load_assignment:
      cluster_name: xds_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: host.docker.internal
                port_value: 18000
    http2_protocol_options:
      connection_keepalive:
        interval: 30s
        timeout: 5s
    upstream_connection_options:
      # configure a TCP keep-alive to detect and reconnect to the admin
      # server in the event of a TCP socket half open connection
      tcp_keepalive: {}
```

 grpc server main.go

```
package main

import (
	"context"
	"flag"
	"fmt"
	"log"
	"net"
	"os"

	core "github.com/envoyproxy/go-control-plane/envoy/config/core/v3"
	route "github.com/envoyproxy/go-control-plane/envoy/config/route/v3"
	clusterservice "github.com/envoyproxy/go-control-plane/envoy/service/cluster/v3"
	discoverygrpc "github.com/envoyproxy/go-control-plane/envoy/service/discovery/v3"
	endpointservice "github.com/envoyproxy/go-control-plane/envoy/service/endpoint/v3"
	listenerservice "github.com/envoyproxy/go-control-plane/envoy/service/listener/v3"
	routeservice "github.com/envoyproxy/go-control-plane/envoy/service/route/v3"
	runtimeservice "github.com/envoyproxy/go-control-plane/envoy/service/runtime/v3"
	secretservice "github.com/envoyproxy/go-control-plane/envoy/service/secret/v3"
	"github.com/envoyproxy/go-control-plane/pkg/cache/types"
	"github.com/envoyproxy/go-control-plane/pkg/cache/v3"
	"github.com/envoyproxy/go-control-plane/pkg/server/v3"
	"github.com/envoyproxy/go-control-plane/pkg/test/v3"
	"google.golang.org/grpc"
)

var (
	port     uint
	basePort uint
	mode     string

	nodeID string
)

func init() {

	// The port that this xDS server listens on
	flag.UintVar(&port, "port", 18000, "xDS management server port")

	// Tell Envoy to use this Node ID
	flag.StringVar(&nodeID, "nodeID", "test-id", "Node ID")
}

func main() {
	flag.Parse()

	// Create a cache
	cache := cache.NewSnapshotCache(false, cache.IDHash{}, nil)

	// Create the snapshot that we'll serve to Envoy
	snapshot := generateSnapshot()

	log.Printf("will serve snapshot %+v", snapshot)

	// Add the snapshot to the cache
	if err := cache.SetSnapshot(nodeID, snapshot); err != nil {
		log.Printf("snapshot error %q for %+v", err, snapshot)
		os.Exit(1)
	}

	// Run the xDS server
	ctx := context.Background()
	cb := &test.Callbacks{Debug: true}
	srv := server.NewServer(ctx, cache, cb)
	RunServer(ctx, srv, port)
}

func RunServer(ctx context.Context, srv server.Server, port uint) {
	// gRPC golang library sets a very small upper bound for the number gRPC/h2
	// streams over a single TCP connection. If a proxy multiplexes requests over
	// a single connection to the management server, then it might lead to
	// availability problems.
	var grpcOptions []grpc.ServerOption
	grpcOptions = append(grpcOptions, grpc.MaxConcurrentStreams(1000000))
	grpcServer := grpc.NewServer(grpcOptions...)

	lis, err := net.Listen("tcp", fmt.Sprintf(":%d", port))
	if err != nil {
		log.Fatal(err)
	}

	// register services
	discoverygrpc.RegisterAggregatedDiscoveryServiceServer(grpcServer, srv)
	endpointservice.RegisterEndpointDiscoveryServiceServer(grpcServer, srv)
	clusterservice.RegisterClusterDiscoveryServiceServer(grpcServer, srv)
	routeservice.RegisterRouteDiscoveryServiceServer(grpcServer, srv)
	listenerservice.RegisterListenerDiscoveryServiceServer(grpcServer, srv)
	secretservice.RegisterSecretDiscoveryServiceServer(grpcServer, srv)
	runtimeservice.RegisterRuntimeDiscoveryServiceServer(grpcServer, srv)

	log.Printf("management server listening on %d\n", port)
	if err = grpcServer.Serve(lis); err != nil {
		log.Println(err)
	}
}

func generateSnapshot() cache.Snapshot {
	routeConfig := &route.RouteConfiguration{
		Name: "test-route",
		VirtualHosts: []*route.VirtualHost{
			&route.VirtualHost{
				Name:    "nase",
				Domains: []string{"*"},
				Routes: []*route.Route{
					&route.Route{
						Match: &route.RouteMatch{
							PathSpecifier: &route.RouteMatch_Prefix{
								Prefix: "/",
							},
						},
						Action: &route.Route_DirectResponse{
							DirectResponse: &route.DirectResponseAction{
								Status: uint32(200),
								Body: &core.DataSource{
									Specifier: &core.DataSource_InlineString{InlineString: "Hello World\n"},
								},
							},
						},
					},
				},
			},
		},
	}

	return cache.NewSnapshot(
		"1", //version
		//time.Now().Format("20060102150405"),
		nil,                           //clusters
		nil,                           //endpoints
		[]types.Resource{routeConfig}, //routes
		nil,                           //listeners
		nil,                           //runtimes
		nil,                           //secrets
	)

}
```
