### ISSUE TITLE
How to update CDS and EDS with ads

### ISSUE THREAD

**Issue by 670205427** [envoyproxy/go-control-plane#522]
I want to use go control plane as the management server to distribute the configuration to envoy, but when I want to modify some configurations (such as load balancing configuration) after the initial distribution, the distribution fails often, and the configuration of EDS will be lost. In the Journal of envoy, I found XXX printed. Is there a problem with my configuration?

### This is my envoy configuration file.

```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }
node:
  cluster: default
  id: default

static_resources:
  clusters:
    - name: xds_cluster
      type: STATIC
      connect_timeout: 1s
      load_assignment:
        cluster_name: xds_cluster
        endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 172.31.8.6 #this is xds server ip
                    port_value: 7000 # port
      typed_extension_protocol_options:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          explicit_http_config:
            http2_protocol_options:
              connection_keepalive:
                interval: 30s
                timeout: 5s
dynamic_resources:
  ads_config:
    api_type: GRPC
    transport_api_version: V3
    grpc_services:
    - envoy_grpc:
        cluster_name: xds_cluster
    set_node_on_first_message_only: true
  cds_config:
    resource_api_version: V3
    ads: {}
  lds_config:
    resource_api_version: V3
    ads: {}
```

### This is my XDS management service code

```
func Main()  {
	signal := make(chan struct{})
	go NewControlPlane(7000,signal)
	select {
	case <-signal:
		break
	case <-time.After(1 * time.Minute):
		log.Println("timeout waiting for the first request")
		os.Exit(1)
	}
	log.Println("initial snapshot ")

	lds := MakeTestLds("default", "Ads")
	rds := MakeTestRds("default")
	eds := MakeTestEds()
	for i := 0; i < 100; i++ {
		var cds []types.Resource
		if i%2==0 {
			logger.Infof("lb is random")

			cds = MakeTestCds("Ads", cluster.Cluster_RANDOM)
		}else {
			logger.Infof("lb is least_request")

			cds = MakeTestCds("Ads", cluster.Cluster_LEAST_REQUEST)
		}
		snapshot, _ := cachev3.NewSnapshot(fmt.Sprintf("v%d", i), map[resource.Type][]types.Resource{
			resource.EndpointType: eds,
			resource.ClusterType:  cds,
			resource.ListenerType: lds,
			resource.RouteType:    rds,
		})
		if err := snapshot.Consistent() ; err!= nil{
			logger.Infof("snapshot inconsistency: %+v\n%+v\n", snapshot, err)
		}
		DefaultCache.SetSnapshot(context.Background(), "default", snapshot)
		EdsCache.SetResources(snapshot.GetResources(resource.EndpointType))
		time.Sleep(time.Second * 30)
	}
}

func MakeTestEds() []types.Resource {
	return []types.Resource{
		&endpoint.ClusterLoadAssignment{
			ClusterName: "my-cluster",
			Endpoints: []*endpoint.LocalityLbEndpoints{
				{
					LbEndpoints: []*endpoint.LbEndpoint{
						{
							HostIdentifier: &endpoint.LbEndpoint_Endpoint{
								Endpoint: &endpoint.Endpoint{
									Address: &core.Address{
										Address: &core.Address_SocketAddress{
											SocketAddress: &core.SocketAddress{
												Protocol: core.SocketAddress_TCP,
												Address:  "127.0.0.1",
												PortSpecifier: &core.SocketAddress_PortValue{
													PortValue: 12345,
												},
											},
										},
									},
								},
							},
						},
						{
							HostIdentifier: &endpoint.LbEndpoint_Endpoint{
								Endpoint: &endpoint.Endpoint{
									Address: &core.Address{
										Address: &core.Address_SocketAddress{
											SocketAddress: &core.SocketAddress{
												Protocol: core.SocketAddress_TCP,
												Address:  "127.0.0.1",
												PortSpecifier: &core.SocketAddress_PortValue{
													PortValue: 12346,
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
	}
}

func MakeTestCds(mode string, lbPolicy cluster.Cluster_LbPolicy) []types.Resource {
	edsSource := configSource(mode)
	connectTimeout := 5 * time.Second
	return []types.Resource{
		&cluster.Cluster{
			Name:                 "my-cluster",
			LbPolicy:             lbPolicy,
			ConnectTimeout:       durationpb.New(connectTimeout),
			ClusterDiscoveryType: &cluster.Cluster_Type{Type: cluster.Cluster_EDS},
			EdsClusterConfig: &cluster.Cluster_EdsClusterConfig{
				EdsConfig: edsSource,
			},
		},
	}
}

func configSource(mode string) *core.ConfigSource {
	source := &core.ConfigSource{
		InitialFetchTimeout: &duration.Duration{Seconds: 15},
	}
	source.ResourceApiVersion = resource.DefaultAPIVersion
	switch mode {
	case "Ads":
		source.ConfigSourceSpecifier = &core.ConfigSource_Ads{
			Ads: &core.AggregatedConfigSource{},
		}
	case "Xds":
		source.ConfigSourceSpecifier = &core.ConfigSource_ApiConfigSource{
			ApiConfigSource: &core.ApiConfigSource{
				TransportApiVersion:       resource.DefaultAPIVersion,
				ApiType:                   core.ApiConfigSource_GRPC,
				SetNodeOnFirstMessageOnly: true,
				GrpcServices: []*core.GrpcService{{
					TargetSpecifier: &core.GrpcService_EnvoyGrpc_{
						EnvoyGrpc: &core.GrpcService_EnvoyGrpc{ClusterName: "xds_cluster"},
					},
				}},
			},
		}
	case "Rest":
		source.ConfigSourceSpecifier = &core.ConfigSource_ApiConfigSource{
			ApiConfigSource: &core.ApiConfigSource{
				ApiType:             core.ApiConfigSource_REST,
				TransportApiVersion: resource.DefaultAPIVersion,
				ClusterNames:        []string{"xds_cluster"},
				RefreshDelay:        durationpb.New(10),
			},
		}
	}
	return source
}
```

### However, sometimes the EDS configuration is lost,which is a normal cluster configuration
```
my-cluster::observability_name::my-cluster
my-cluster::default_priority::max_connections::1024
my-cluster::default_priority::max_pending_requests::1024
my-cluster::default_priority::max_requests::1024
my-cluster::default_priority::max_retries::3
my-cluster::high_priority::max_connections::1024
my-cluster::high_priority::max_pending_requests::1024
my-cluster::high_priority::max_requests::1024
my-cluster::high_priority::max_retries::3
my-cluster::added_via_api::true
my-cluster::127.0.0.1:12345::cx_active::0
my-cluster::127.0.0.1:12345::cx_connect_fail::0
my-cluster::127.0.0.1:12345::cx_total::0
my-cluster::127.0.0.1:12345::rq_active::0
my-cluster::127.0.0.1:12345::rq_error::0
my-cluster::127.0.0.1:12345::rq_success::0
my-cluster::127.0.0.1:12345::rq_timeout::0
my-cluster::127.0.0.1:12345::rq_total::0
my-cluster::127.0.0.1:12345::hostname::
my-cluster::127.0.0.1:12345::health_flags::healthy
my-cluster::127.0.0.1:12345::weight::1
my-cluster::127.0.0.1:12345::region::
my-cluster::127.0.0.1:12345::zone::
my-cluster::127.0.0.1:12345::sub_zone::
my-cluster::127.0.0.1:12345::canary::false
my-cluster::127.0.0.1:12345::priority::0
my-cluster::127.0.0.1:12345::success_rate::-1.0
my-cluster::127.0.0.1:12345::local_origin_success_rate::-1.0
my-cluster::127.0.0.1:12346::cx_active::0
my-cluster::127.0.0.1:12346::cx_connect_fail::0
my-cluster::127.0.0.1:12346::cx_total::0
my-cluster::127.0.0.1:12346::rq_active::0
my-cluster::127.0.0.1:12346::rq_error::0
my-cluster::127.0.0.1:12346::rq_success::0
my-cluster::127.0.0.1:12346::rq_timeout::0
my-cluster::127.0.0.1:12346::rq_total::0
my-cluster::127.0.0.1:12346::hostname::
my-cluster::127.0.0.1:12346::health_flags::healthy
my-cluster::127.0.0.1:12346::weight::1
my-cluster::127.0.0.1:12346::region::
my-cluster::127.0.0.1:12346::zone::
my-cluster::127.0.0.1:12346::sub_zone::
my-cluster::127.0.0.1:12346::canary::false
my-cluster::127.0.0.1:12346::priority::0
my-cluster::127.0.0.1:12346::success_rate::-1.0
my-cluster::127.0.0.1:12346::local_origin_success_rate::-1.0
xds_cluster::observability_name::xds_cluster
xds_cluster::default_priority::max_connections::1024
xds_cluster::default_priority::max_pending_requests::1024
xds_cluster::default_priority::max_requests::1024
xds_cluster::default_priority::max_retries::3
xds_cluster::high_priority::max_connections::1024
xds_cluster::high_priority::max_pending_requests::1024
xds_cluster::high_priority::max_requests::1024
xds_cluster::high_priority::max_retries::3
xds_cluster::added_via_api::false
xds_cluster::172.31.8.6:7000::cx_active::1
xds_cluster::172.31.8.6:7000::cx_connect_fail::0
xds_cluster::172.31.8.6:7000::cx_total::1
xds_cluster::172.31.8.6:7000::rq_active::1
xds_cluster::172.31.8.6:7000::rq_error::0
xds_cluster::172.31.8.6:7000::rq_success::0
xds_cluster::172.31.8.6:7000::rq_timeout::0
xds_cluster::172.31.8.6:7000::rq_total::1
xds_cluster::172.31.8.6:7000::hostname::
xds_cluster::172.31.8.6:7000::health_flags::healthy
xds_cluster::172.31.8.6:7000::weight::1
xds_cluster::172.31.8.6:7000::region::
xds_cluster::172.31.8.6:7000::zone::
xds_cluster::172.31.8.6:7000::sub_zone::
xds_cluster::172.31.8.6:7000::canary::false
xds_cluster::172.31.8.6:7000::priority::0
xds_cluster::172.31.8.6:7000::success_rate::-1.0
xds_cluster::172.31.8.6:7000::local_origin_success_rate::-1.0
```
### which is the cluster configuration when it is lost
```
my-cluster::observability_name::my-cluster
my-cluster::default_priority::max_connections::1024
my-cluster::default_priority::max_pending_requests::1024
my-cluster::default_priority::max_requests::1024
my-cluster::default_priority::max_retries::3
my-cluster::high_priority::max_connections::1024
my-cluster::high_priority::max_pending_requests::1024
my-cluster::high_priority::max_requests::1024
my-cluster::high_priority::max_retries::3
my-cluster::added_via_api::true
xds_cluster::observability_name::xds_cluster
xds_cluster::default_priority::max_connections::1024
xds_cluster::default_priority::max_pending_requests::1024
xds_cluster::default_priority::max_requests::1024
xds_cluster::default_priority::max_retries::3
xds_cluster::high_priority::max_connections::1024
xds_cluster::high_priority::max_pending_requests::1024
xds_cluster::high_priority::max_requests::1024
xds_cluster::high_priority::max_retries::3
xds_cluster::added_via_api::false
xds_cluster::172.31.8.6:7000::cx_active::1
xds_cluster::172.31.8.6:7000::cx_connect_fail::0
xds_cluster::172.31.8.6:7000::cx_total::1
xds_cluster::172.31.8.6:7000::rq_active::1
xds_cluster::172.31.8.6:7000::rq_error::0
xds_cluster::172.31.8.6:7000::rq_success::0
xds_cluster::172.31.8.6:7000::rq_timeout::0
xds_cluster::172.31.8.6:7000::rq_total::1
xds_cluster::172.31.8.6:7000::hostname::
xds_cluster::172.31.8.6:7000::health_flags::healthy
xds_cluster::172.31.8.6:7000::weight::1
xds_cluster::172.31.8.6:7000::region::
xds_cluster::172.31.8.6:7000::zone::
xds_cluster::172.31.8.6:7000::sub_zone::
xds_cluster::172.31.8.6:7000::canary::false
xds_cluster::172.31.8.6:7000::priority::0
xds_cluster::172.31.8.6:7000::success_rate::-1.0
xds_cluster::172.31.8.6:7000::local_origin_success_rate::-1.0
```

###This is envoy's log

<img width="1380" alt="企业微信截图_7fc7a089-be3e-47c3-b8b8-640b0b66cf49" src="https://user-images.githubusercontent.com/30279937/145143190-c196b590-7810-4612-a143-6736571dedf0.png">
