### ISSUE TITLE
Envoy proxy stops updating through XDS server

### ISSUE THREAD

**Issue by renuka-fernando** [envoyproxy/go-control-plane#566]
## Description

Envoy is serving (proxing) for existing routes, clusters, etc. but it is not updating via the SotW xDS gRPC server for new routes, clusters, etc.

Envoy version: v1.20.0
Go control plane version: v0.10.0 - simple cache
SotW xDS gRPC server

Two replicas of envoy and two replicas of xDS servers are running for HA purposes. We identified that one replica of the envoy was updated properly and the other one stopped updating. But both envoy replicas serve for downstream requests with their existing route, and cluster configs.

### Config
```yaml
{
    "static_resources": {
        "clusters": [
            {
                "name": "xds_cluster",
                "type": "STRICT_DNS",
                "connect_timeout": "1s",
                "transport_socket": {
                    "name": "envoy.transport_sockets.tls",
                    "typed_config": {
                        "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext",
                        "common_tls_context": {...}
                    }
                },
                "load_assignment": {
                    "cluster_name": "xds_cluster",
                    "endpoints": [
                        {
                            "lb_endpoints": [
                                {
                                    "endpoint": {
                                        "address": {
                                            "socket_address": {
                                                "address": "xds-server",
                                                "port_value": 10000
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    ]
                },
                "typed_extension_protocol_options": {
                    "envoy.extensions.upstreams.http.v3.HttpProtocolOptions": {
                        "@type": "type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions",
                        "explicit_http_config": {
                            "http2_protocol_options": {}
                        }
                    }
                }
            }
        ]
    },
    "dynamic_resources": {
        "lds_config": {
            "ads": {},
            "resource_api_version": "V3"
        },
        "cds_config": {
            "ads": {},
            "resource_api_version": "V3"
        },
        "ads_config": {
            "api_type": "GRPC",
            "grpc_services": [
                {
                    "envoy_grpc": {
                        "cluster_name": "xds_cluster"
                    }
                }
            ],
            "transport_api_version": "V3"
        }
    }
}
```

We have also created an issue on the envoy proxy side https://github.com/envoyproxy/envoy/issues/21107 since we do not exactly know the issue caused from the envoy or from go-control-plane
