### ISSUE TITLE
Should auth.AttributeContext_HttpRequest.GetRawBody always return a complete slice of bytes received?

### ISSUE THREAD

**Issue by leefernandes** [envoyproxy/go-control-plane#642]
We've encountered an issue when sending messages over `9632` characters, `GetRawBody()` does not include all of the bytes sent, it's noticeably truncated at character 9633.  

We are using the default GRPC incoming message limit of 4mb.
We are routing through Istio gateway to our authorization service with an AuthorizationPolicy.  
Our extension provider configuration  has a maxRequestBytes value of 4096.
We are using  `github.com/envoyproxy/go-control-plane v0.11.0`

```go
import auth "github.com/envoyproxy/go-control-plane/envoy/service/auth/v3"

b := r.Attributes.Request.GetHttp().GetRawBody()
```

```yaml
meshConfig:
  extensionProviders:
    - name: "ext-authz.local"
      envoyExtAuthzGrpc:
        service: "ext-authz.local"
        port: "50052"
        includeRequestBodyInCheck:
          maxRequestBytes: 4096
          packAsBytes: true
```
